version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting-api
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: npm run dev
    expose:
      - 3333
    ports:
      - "3333:3333"
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: meeting-db
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - .env
    ports:
      - "3306:3306"
