name: Deploy To Beanstalk
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r ../deploy.zip . -x '*.git*'

      - name: Set unique version number
        run: echo "VERSION=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v11
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          application_name: meeting-app
          environment_name: Meetingapp-env
          version_label: "1.1.5"
          region: ap-northeast-1
          deployment_package: ../deploy.zip

      - name: AWS Deployed!
        run: echo App deployed to ELB
